app:
  telegram-token: "6084238422:AAH-0qZf9gQvsdKmJbjCipJmPPZmd-fJB24" # Замените на ваш действительный токен в ${TELEGRAM_BOT_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
