app:
  telegram-token: ${TELEGRAM_BOT_TOKEN} # Замените на ваш действительный токен в ${TELEGRAM_BOT_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

api:
  scrapper:
    base-url: http://localhost:8090
